@baseUrl = http://localhost:2001

### 
GET {{baseUrl}}/threads/3053617
###
POST {{baseUrl}}/threads/305343617

###
GET {{baseUrl}}/threads/thread/thread_wPCAYHX8xymFN9hVEhZ99ztg

###
GET {{baseUrl}}/threads/305343617

###
DELETE {{baseUrl}}/threads/thread_CcidvyijcWD7dFgIK1q35oDE

###
POST {{baseUrl}}/threads/3343617/Раскажи%20анегдот%21

###
POST {{baseUrl}}/threads/add-image/thread_ooTrQLcadx7NTWQlNS0D7AHU
content-type: application/json

{
 "message": "This is a test message",
 "fileId": "file-7HG0mBLXjOsDSaSZ5o7hCjBS"
}